global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'seeder'
    static_configs:
      - targets: ['seeder:8000']
    metrics_path: '/metrics'

  - job_name: 'simulation'
    static_configs:
      - targets: ['simulation:8000']
    metrics_path: '/metrics'